apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - node
            - dist/index.js
          env:
            - name: BEARER_TOKEN
            - name: ENVIRONMENT_TYPE
            - name: JWT_SECRET
            - name: REFRESH_TOKEN_SECRET
            - name: TZ
          image: backend
          name: backend
          ports:
            - containerPort: 4000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/database
              name: db-data
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
