apiVersion: v1 # API version for ConfigMap resource
kind: ConfigMap # The type of resource
metadata:
  name: nginx-config # Name of the ConfigMap
data: # Key-value pairs for configuration data
  nginx.conf: | # The pipe symbol allows multi-line text
    server {
      listen 80;
      server_name localhost;
      
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
      
      location /hello {
        return 200 'Hello from Kubernetes ConfigMap!\n';
      }
    }
  index.html: | # Another key with multi-line value
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes Demo</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          text-align: center;
        }
        .container {
          background-color: #f8f9fa;
          border-radius: 8px;
          padding: 20px;
          margin-top: 20px;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
          color: #326CE5;
        }
      </style>
    </head>
    <body>
      <h1>Kubernetes Demo</h1>
      <div class="container">
        <h2>Hello from Kubernetes!</h2>
        <p>This page is served from a Nginx pod in your Kubernetes cluster.</p>
      </div>
    </body>
    </html>
